### ISSUE TITLE
[Feature] Network inspect

### ISSUE THREAD

**Issue by Gsonovb** [microsoft/vscode-react-native#1418]
# 🚀 Feature request

 Network Inspect

## What scenarios will this solve?

Check the back-end API call,
Displaying the call status on the mobile device will overwrite the operation screen

### Implementation plan
- [x] Implement the server side of the Network inspector 
- [x] Implement communication with devices and emulators
  - [x] Implement communication with Android devices
  - [x] Implement communication with Android emulators
  - [x] Implement communication with iOS devices
  - [x] Implement communication with iOS simulators
- [x] Implement displaying of network requests data
- [x] Add tests for the Network inspector
- [x] Add documentation for the Network inspector

**Comment by JiglioNero** [comment]
Hi @Gsonovb and thanks for your feedback. What do you mean by:
Displaying the call status on the mobile device will overwrite the operation screen
Also could you please add more context on what exact features do you want to see in extension and how do you want to use them? What backend API calls do you want to check and how? This information will be very helpful for us.

**Comment by Gsonovb** [comment]
In my case,

Help friends maintain the program,

They use firebase,

But I want to use it in China,

So we use the forwarding service (replacing the URL of the firebase package),

Sometimes there are problems with the request service, you need to check whether the forwarding service is normal.

I can't access the back-end source code and forwarding server. I can only record the request information through the tool and send it to them for testing.

**Comment by SounD120** [comment]
@Gsonovb This extension is for debugging the React Native application source code. If I understand you correctly you want to debug the source code remotely on other machine? If it so: you need to modify `address` and `port` arguments in your `Attach to packager` scenario. But otherwise I think that this is not the thing that might be done with the React Native Tools extension.

**Comment by molant** [comment]
@SounD120 I believe what @Gsonovb wants is to be able to see what network requests are being done by the React Native application and the contents of the responses, similar to the Network tab in the Chrome Developer Tools.

Am I right?

**Comment by Gsonovb** [comment]
@molant   Yes，

React can view the request in the web tag in chrome developer tools, but react native runs on the device and cannot be viewed on the computer.

**Comment by SounD120** [comment]
@Gsonovb Got it. We'll consider adding this feature in order of priorities.

**Comment by RedMickey** [comment]
We have investigated ways to display network requests data in the extension and found out the following three ways to do it:

1. **In output channel in VS Code**. In this case, all the messages are printed in their full size. The screenshot below is just a draft, which doesn't contain all the information about the requests.
    ![image](https://user-images.githubusercontent.com/33267199/106253517-a3b9aa80-6228-11eb-8eed-e6e8ec7e14de.png)

2. **In VS Code DevTools console**. In the console  we can open and hide properties, this allows to show information in more readable form. However, in this case our network inspector outputs will mix with some other VS Code messages. Below there is an example of printing raw request data. If this way is chosen to implement displaying of network requests data, we will process that data to show only useful information properly. 
    ![Screen Shot 2021-01-28 at 17 18 17](https://user-images.githubusercontent.com/33267199/106254457-c6988e80-6229-11eb-8a87-6acc68f62df7.png)

3. **In VS Code Webview**. We could create a web client for our Network inspector backend and run it inside the VS Code webview. We made up prototypes of UI of our Network inspector. We suppose that the Network inspector page should be opened at the second editor column in VS Code, so users could see the application code and requests data at the same time. Below there are prototypes of UI of the inspector.
    ![image](https://user-images.githubusercontent.com/33267199/106256648-9b636e80-622c-11eb-9c9e-581c342a2fb1.png)
    This is a prototype of the main page of the inspector. It contains a list with requests. Requests rows are clickable. If a user click on a row, details data of the request will be shown below the row.
    ![image](https://user-images.githubusercontent.com/33267199/106256728-b33af280-622c-11eb-887f-12d164a12994.png)
    Details data of the request contains general request data, request and response headers, response body and, optionally, query strings parameters. Request header, response headers, response body and query strings parameters are extensible, this allows to show only needed information.

We'd like to discuss which way of displaying network requests data is more preferable to be implemented. Below there is a survey in which you can select the way you consider is the best.

[![](https://api.gh-polls.com/poll/01EX6RWSE7AKCFS5JQ8J6QAQRX/Display%20requests%20data%20in%20output%20channel%20in%20VS%20Code)](https://api.gh-polls.com/poll/01EX6RWSE7AKCFS5JQ8J6QAQRX/Display%20requests%20data%20in%20output%20channel%20in%20VS%20Code/vote)
[![](https://api.gh-polls.com/poll/01EX6RWSE7AKCFS5JQ8J6QAQRX/Display%20requests%20data%20in%20VS%20Code%20DevTools%20console)](https://api.gh-polls.com/poll/01EX6RWSE7AKCFS5JQ8J6QAQRX/Display%20requests%20data%20in%20VS%20Code%20DevTools%20console/vote)
[![](https://api.gh-polls.com/poll/01EX6RWSE7AKCFS5JQ8J6QAQRX/Display%20requests%20data%20in%20VS%20Code%20Webview)](https://api.gh-polls.com/poll/01EX6RWSE7AKCFS5JQ8J6QAQRX/Display%20requests%20data%20in%20VS%20Code%20Webview/vote)

We will be glad to see your feedback about Network inspector UI.

**Comment by Gsonovb** [comment]
I like to be in VSCode Webview.

Just like the developer tools in the Chromium browser, multiple resources are loaded on a page, but there may be only one or two errors (HTTP 40X, 50X)

**Comment by gorhom** [comment]
`output channel in VS Code` and `VS Code DevTools console` both looks good and practical

**Comment by matijagrcic** [comment]
Looks good but Flipper already has this https://fbflipper.com/docs/features/react-native/.
DevTools console looks like a best option as you really only want this when debugging.

**Comment by RedMickey** [comment]
Hi guys and thanks for your feedback.

@matijagrcic, with respect to [Flipper Network inspector](https://fbflipper.com/docs/features/react-native/), the idea of our Network inspector is to work in a tab in VS Code, so It wouldn't be necessary to open Flipper application while debugging a React Native app in VS Code. It could be more convenient to use one development tool for this purpose instead of switching between the two applications.

**Comment by RedMickey** [comment]
Hi everyone,
in the first version of the Network inspector, we decided to implement displaying of network requests data in VSCode DevTools console, and now we are working on it.
We've implemented a preview version of possible displaying of network requests data in the console. In the screenshots below you can see how it looks now:

- Light DevTools console theme
![Screen Shot 2021-03-23 at 16 43 40](https://user-images.githubusercontent.com/33267199/112156186-0f037580-8bf7-11eb-9cb4-f824fbe0dfe8.png)

- Dark DevTools console theme
![Screen Shot 2021-03-23 at 16 41 02](https://user-images.githubusercontent.com/33267199/112156202-11fe6600-8bf7-11eb-8a83-e10ff38e15e1.png)

We'd like to discuss the current appearance of requests data in the console. It could be that we should make some changes to the data structure or change the logs colors to more appropriate ones. We will be grateful for your advice and suggestions.

CC @EricCornelson, @molant Could you please also look at this?

**Comment by RedMickey** [comment]
Hi everyone, we have implemented the Network inspector feature. It will be available in the next release.
