### ISSUE TITLE
Enhance extension smoke tests

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-react-native#1441]
There are plans to improve the extensions smoke tests. This should help to decrease tests flakiness and speed up the tests execution.
Here is the preliminary plan:
- [x] Update [`WebDriverIO`](https://github.com/webdriverio/webdriverio) to the latest version that is supported by [`appium`](https://github.com/appium/appium) #1442
- [x] Use [`vscode-test`](https://github.com/microsoft/vscode-test) package in order to download VS Code for the tests and remove the approach that is used currently #1443
- [x] Update VS Code version for the tests to latest #1446
- [x] Implement test applications caching in order to decrease tests deployment stage time (?)
    - [x] Implement retention policy for the cache (how much versions of each app we should store locally)
    - [x] Investigate necessity of VS Code test repository caching
- [x] [Overall smoke tests code refactoring](https://github.com/microsoft/vscode-react-native/issues/1445)
- [x] ~~Join smoke tests for all platforms in one CI pipeline (?)~~
- [x] Add tests for recently added platforms like macOS and Windows
- [x] Enhance tests logging
    - [x] Colorize tests logs
    - [x] Improve logs handling, unload main stdout thread
- [x] Investigate the possibility to get rid of Appium in native Android and iOS for enabling Remote JS debug and replace this approach by NativeModules usage
- [x] Investigate the possibility to change installation stage for pure Expo tests using bare templates from Expo CLI
